from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

class Store(ABC):
    """Barcha storage backendlari uchun yagona interfeys."""
    backend_name: str = "base"

    # USERS
    @abstractmethod
    async def get_user_by_tg(self, telegram_id: int) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def get_user(self, user_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def create_user(self, user: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def update_user(self, user_id: str, fields: Dict[str, Any]) -> bool: ...
    @abstractmethod
    async def list_users(self, limit: int = 200) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def count_users(self) -> int: ...

    # COURSES
    @abstractmethod
    async def list_courses(self, published_only: bool = True) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def get_course(self, id_or_slug: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def get_course_by_channel_id(self, channel_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def upsert_course(self, course: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def delete_course(self, course_id: str) -> bool: ...
    @abstractmethod
    async def seed_course_structure(self, course_id: str, modules: List[Dict[str, Any]]) -> bool: ...

    # PURCHASES
    @abstractmethod
    async def create_purchase(self, p: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def get_purchase_by_tx(self, transaction_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def get_purchase_by_invite_link(self, invite_link: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def update_purchase(self, purchase_id: str, fields: Dict[str, Any]) -> bool: ...
    @abstractmethod
    async def transition_purchase_status(
        self, purchase_id: str, expected_status: str, fields: Dict[str, Any]
    ) -> bool: ...
    @abstractmethod
    async def list_purchases(self, status: Optional[str] = None, limit: int = 50) -> List[Dict[str, Any]]: ...

    # ENROLLMENTS
    @abstractmethod
    async def get_enrollment(self, user_id: str, course_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def create_enrollment(self, user_id: str, course_id: str, purchase_id: Optional[str] = None) -> Dict[str, Any]: ...
    @abstractmethod
    async def list_enrollments(self, user_id: str) -> List[Dict[str, Any]]: ...

    # LESSON PROGRESS
    @abstractmethod
    async def upsert_progress(self, user_id: str, course_id: str, lesson_id: str, completed: bool, last_position: int = 0) -> bool: ...
    @abstractmethod
    async def get_progress_map(self, user_id: str, course_id: str) -> Dict[str, Dict[str, Any]]: ...
    @abstractmethod
    async def count_completed(self, user_id: str, course_id: str) -> int: ...
    @abstractmethod
    async def latest_progress_row(self, user_id: str, course_id: str) -> Optional[Dict[str, Any]]: ...

    # CERTIFICATES
    @abstractmethod
    async def list_certificates(self, user_id: str) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def create_certificate(self, cert: Dict[str, Any]) -> Dict[str, Any]: ...

    # NOTIFICATIONS
    @abstractmethod
    async def list_notifications(self, user_id: str, limit: int = 20) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def create_notification(self, user_id: str, title: str, message: str, type_: str = "info") -> Dict[str, Any]: ...
    @abstractmethod
    async def mark_notifications_read(self, user_id: str) -> bool: ...

    # STATS
    @abstractmethod
    async def revenue_stats(self) -> Dict[str, int]: ...
    @abstractmethod
    async def broadcast_recipients(self) -> List[Dict[str, Any]]: ...
